variables:
  DOCKER_URL: "$DOCKER_USER"/"$DOCKER_REPO"

stages:
  - test
  - build
  - deploy

default:
  image: docker:cli

.run_when:
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /(api|all).*/ || $CI_COMMIT_DESCRIPTION =~ /(api|all).*/

# test_project:
#   stage: test
#   extends:
#     - .run_when
#   coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
#   script:
#     - npm install
#     - npm run test
#   cache:
#     paths:
#       - node_modules/
#   artifacts:
#     reports:
#       junit:
#         - junit.xml
#     paths:
#       - node_modules/

before_script:
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"

build_project:
  stage: build
  extends:
    - .run_when
  services:
    - docker:dind
  # dependencies:
  #   - test_project
  script:
    - docker build -t "$DOCKER_USER"/"$DOCKER_REPO" api-portal
    - docker push "$DOCKER_USER"/"$DOCKER_REPO"
  # artifacts:
  #   when: always
  #   paths:
  #     - "build/"
# deploy_project:
#   stage: deploy
#   extends:
#     - .run_when
#   dependencies:
#     - build_project
#   script:
#     - mv build/ public/
#   artifacts:
#     when: always
#     paths:
#       - "public/"

